title: Vibha Ganji's Blog
description: "August 2023 to June 2024"
owner_name: Vibha Ganji
github_username: vibha-yganji
github_repo: "vibha-teacher_portfolio"
baseurl: "/vibha-teacher_portfolio"
future: true
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders/teacher_portfolio"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }      
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.html


